# Generated by Django 4.2.5 on 2023-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='location',
            field=models.CharField(help_text='Enter exact address location.', max_length=200),
        ),
    ]
