# Generated by Django 4.2.5 on 2023-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos', '0002_alter_eventsubmission_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
