# Generated by Django 4.2.7 on 2023-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos', '0003_eventsubmission_latitude_eventsubmission_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='tag',
            field=models.CharField(choices=[(None, 'No Tags'), ('sports', 'Sports'), ('social', 'Social'), ('food', 'Food'), ('career fair', 'Career Fair')], max_length=200, null=True),
        ),
    ]
