# Generated by Django 4.2.7 on 2023-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos', '0004_eventsubmission_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='tag',
            field=models.CharField(choices=[(None, 'No Tags'), ('career', 'Career'), ('club', 'Club'), ('arts & sciences', 'Arts and Sciences'), ('concert', 'Concert'), ('culture', 'Culture'), ('education', 'Education'), ('engineering', 'Engineering'), ('food', 'Food'), ('mcintire', 'McIntire'), ('religious', 'Religious'), ('social', 'Social'), ('sports', 'Sports'), ('theatre', 'Theatre')], max_length=200, null=True),
        ),
    ]
