# Generated by Django 4.2.7 on 2023-11-22 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos', '0006_eventsubmission_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 20, 17, 19, 710877)),
        ),
    ]
