# Generated by Django 4.2.7 on 2023-12-02 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hoos", "0012_alter_eventsubmission_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubmission",
            name="date_time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
